[mypy]
strict = True
ignore_missing_imports = True
explicit_package_bases = True
disallow_untyped_decorators = False
disallow_subclassing_any = False
plugins = sqlalchemy.ext.mypy.plugin, pydantic.mypy
